/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSavings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChallenges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/challenges/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshChallenges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/challenges/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChallenge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/receipts/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["simulateReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReceipts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/league": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLeague"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/referral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReferral"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/referrals/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeemReferral"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAchievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pm/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPmUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pm/fraud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFraudChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pm/simulation/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestSimulation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pm/eval/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestEval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            database: "ok" | "error";
        };
        UserSummary: {
            id: number;
            pseudonym: string;
            /** @enum {string} */
            segment: "regular_mid" | "light" | "heavy" | "dormant";
            level: number;
        };
        UserListResponse: {
            items: components["schemas"]["UserSummary"][];
        };
        DomovoyState: {
            xp: number;
            level: number;
            xp_to_next_level: number;
            /** @enum {string} */
            mood: "cheerful" | "cozy" | "healthy" | "bored" | "sleepy";
            mood_reason: string;
            streak_weeks: number;
            items: string[];
        };
        SavingsCategory: {
            category: string;
            amount: number;
        };
        SavingsSummary: {
            /** @enum {string} */
            period: "week" | "month";
            amount: number;
            previous_amount: number;
            delta: number;
            discount_amount: number;
            points_earned: number;
            points_spent: number;
            top_categories: components["schemas"]["SavingsCategory"][];
        };
        SavingsResponse: components["schemas"]["SavingsSummary"];
        ChallengeEconomics: {
            avg_basket: number;
            expected_incremental_purchases: number;
            expected_incremental_margin: number;
            max_reward_rub: number;
            contribution_margin: number;
            reward_share_max: number;
        };
        Challenge: {
            id: number;
            /** @enum {string} */
            type: "frequency" | "category";
            category: string | null;
            /** @enum {string} */
            status: "active" | "completed" | "failed" | "expired";
            is_hero: boolean;
            baseline: number;
            target: number;
            progress: number;
            /** Format: date-time */
            period_start: string;
            /** Format: date-time */
            period_end: string;
            reward_xp: number;
            reward_points: number;
            title: string;
            body: string;
        };
        ChallengeDetail: components["schemas"]["Challenge"] & {
            explanation: string;
            rationale_features: {
                [key: string]: unknown;
            };
            economics: components["schemas"]["ChallengeEconomics"];
            /** @enum {string} */
            copy_source: "llm" | "template";
        };
        ChallengeListResponse: {
            hero: components["schemas"]["ChallengeDetail"] | null;
            side: components["schemas"]["ChallengeDetail"][];
            history: components["schemas"]["Challenge"][];
        };
        LeagueTeaser: {
            division: number;
            rank: number;
            size: number;
            /** @enum {string} */
            zone: "promotion" | "safe" | "demotion";
        };
        ReferralTeaser: {
            code: string;
            invited_count: number;
            rewarded_count: number;
        };
        HomeResponse: {
            user: components["schemas"]["UserSummary"];
            domovoy: components["schemas"]["DomovoyState"];
            savings: components["schemas"]["SavingsSummary"];
            insight: string;
            hero_challenge: components["schemas"]["ChallengeDetail"] | null;
            league: components["schemas"]["LeagueTeaser"] | null;
            referral: components["schemas"]["ReferralTeaser"];
            recommended_mechanic: {
                /** @enum {string} */
                mechanic: "challenge" | "league" | "referral";
                reason: string;
            };
        };
        ReceiptItemInput: {
            product_name: string;
            category: string;
            qty: number;
            regular_price: number;
            paid_price: number;
            /** @default false */
            is_promo: boolean;
        };
        ReceiptInput: {
            user_id: number;
            store_id: number;
            /** Format: date-time */
            purchased_at: string;
            /** @default 0 */
            points_earned: number;
            /** @default 0 */
            points_spent: number;
            pos_id?: string | null;
            items: components["schemas"]["ReceiptItemInput"][];
        };
        SimulateReceiptInput: {
            /**
             * @default typical
             * @enum {string}
             */
            scenario: "typical" | "category_boost" | "fraud_burst";
            store_id?: number | null;
        };
        Receipt: {
            id: number;
            store_id: number;
            store_name: string;
            /** Format: date-time */
            purchased_at: string;
            regular_total: number;
            paid_total: number;
            discount_total: number;
            points_earned: number;
            points_spent: number;
            counted: boolean;
            is_returned: boolean;
            items: {
                product_name: string;
                category: string;
                qty: number;
                regular_price: number;
                paid_price: number;
                is_promo: boolean;
            }[];
        };
        ReceiptListResponse: {
            items: components["schemas"]["Receipt"][];
        };
        FraudDecision: {
            score: number;
            /** @enum {string} */
            decision: "approve" | "hold" | "block";
            signals: {
                code: string;
                weight: number;
                strong: boolean;
                detail: string;
            }[];
        };
        ChallengeProgressDelta: {
            challenge_id: number;
            progress_before: number;
            progress_after: number;
            target: number;
            completed: boolean;
            reward_points: number;
            reward_xp: number;
        };
        ReceiptProcessingResult: {
            receipt: components["schemas"]["Receipt"];
            counted: boolean;
            counted_reason: string | null;
            xp_delta: number;
            domovoy: components["schemas"]["DomovoyState"];
            savings_delta: number;
            challenges: components["schemas"]["ChallengeProgressDelta"][];
            league_rank_before: number | null;
            league_rank_after: number | null;
            referral_status: string | null;
            fraud: components["schemas"]["FraudDecision"];
            achievements_unlocked: string[];
        };
        LeagueMember: {
            pseudonym: string;
            level: number;
            score: number;
            rank: number;
            is_me: boolean;
        };
        LeagueResponse: {
            division: number;
            division_name: string;
            /** Format: date */
            week_start: string;
            /** Format: date */
            week_end: string;
            size: number;
            my_rank: number;
            my_score: number;
            /** @enum {string} */
            my_zone: "promotion" | "safe" | "demotion";
            promotion_cutoff: number;
            demotion_cutoff: number;
            members: components["schemas"]["LeagueMember"][];
            house: {
                store_name: string;
                avg_savings_rate: number;
                district_rank: number;
                district_size: number;
            };
        };
        ReferralInvitee: {
            /** @description «Сосед №3», без имён */
            label: string;
            /** @enum {string} */
            referee_kind: "new" | "dormant" | "active";
            /** @enum {string} */
            status: "pending" | "first_purchase" | "qualified" | "on_review" | "rewarded" | "blocked";
            purchases_done: number;
            purchases_required: number;
            reward_points: number;
            /** Format: date-time */
            created_at: string;
        };
        ReferralResponse: {
            code: string;
            link: string;
            rules: string[];
            referrer_reward_points: number;
            referee_reward_points_new: number;
            referee_reward_points_dormant: number;
            invitees: components["schemas"]["ReferralInvitee"][];
            paid_this_month: number;
            paid_limit_month: number;
        };
        RedeemReferralInput: {
            code: string;
            device_fingerprint?: string | null;
            pseudonym?: string | null;
        };
        RedeemReferralResponse: {
            referee_user_id: number;
            referrer_user_id: number;
            /** @enum {string} */
            referee_kind: "new" | "dormant" | "active";
            /** @enum {string} */
            status: "pending" | "first_purchase" | "qualified" | "on_review" | "rewarded" | "blocked";
        };
        Achievement: {
            code: string;
            title: string;
            /** Format: date-time */
            unlocked_at: string;
        };
        AchievementListResponse: {
            items: components["schemas"]["Achievement"][];
        };
        UserFeatures: {
            /** Format: date-time */
            computed_at: string;
            window_weeks: number;
            frequency_per_week: number;
            recency_days: number;
            avg_basket: number;
            promo_sensitivity: number;
            cadence_days: number;
            category_affinity: {
                [key: string]: {
                    share: number;
                    visits: number;
                    cadence_days: number;
                };
            };
            realized_savings_30d: number;
            favourite_store_id: number;
            cross_chain_share: number;
        };
        RewardLedgerEntry: {
            kind: string;
            xp_delta: number;
            points_delta: number;
            ref_type: string | null;
            ref_id: number | null;
            /** Format: date-time */
            created_at: string;
        };
        PmUserResponse: {
            user: components["schemas"]["UserSummary"];
            features: components["schemas"]["UserFeatures"];
            recommended_mechanic: {
                /** @enum {string} */
                mechanic: "challenge" | "league" | "referral";
                reasons: string[];
            };
            hero_challenge: components["schemas"]["ChallengeDetail"] | null;
            rewards_total_points: number;
            rewards_total_xp: number;
            expected_incremental_margin_month: number;
            fraud_checks: components["schemas"]["FraudCheck"][];
            ledger: components["schemas"]["RewardLedgerEntry"][];
        };
        FraudCheck: {
            id: number;
            /** @enum {string} */
            subject_type: "receipt" | "referral";
            subject_id: number;
            user_id: number;
            score: number;
            /** @enum {string} */
            decision: "approve" | "hold" | "block";
            signals: {
                code: string;
                weight: number;
                strong: boolean;
                detail: string;
            }[];
            /** Format: date-time */
            created_at: string;
        };
        FraudCheckListResponse: {
            items: components["schemas"]["FraudCheck"][];
        };
        SimulationRun: {
            id: number;
            /** Format: date-time */
            created_at: string;
            params: {
                [key: string]: unknown;
            };
            results: {
                purchases_per_user_control: number;
                purchases_per_user_treatment: number;
                share_above_n_control: number;
                share_above_n_treatment: number;
                frequency_uplift: number;
                incremental_revenue: number;
                incremental_margin: number;
                reward_cost: number;
                net_effect: number;
                referral_conversion: number;
                fraud_precision: number;
                fraud_recall: number;
            };
        };
        EvalRun: {
            id: number;
            /** Format: date-time */
            created_at: string;
            profiles: number;
            hit_rate: number;
            invalid_rate: number;
            fallback_rate: number;
            economics_pass_rate: number;
            details: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: {
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ошибка валидации */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        UserId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список демо-пользователей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    getHome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Агрегат для экрана Home */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSavings: {
        parameters: {
            query?: {
                period?: "week" | "month";
            };
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Экономия за период */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listChallenges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Активные и завершённые челленджи */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    refreshChallenges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Новый набор на неделю */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
                challenge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Челлендж с объяснением */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    ingestReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptInput"];
            };
        };
        responses: {
            /** @description Чек обработан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptProcessingResult"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    simulateReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulateReceiptInput"];
            };
        };
        responses: {
            /** @description Сгенерированный чек обработан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptProcessingResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReceipts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description История чеков */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Лига пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getReferral: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Реферальная страница */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    redeemReferral: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemReferralInput"];
            };
        };
        responses: {
            /** @description Приглашённый создан и привязан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemReferralResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Лимит приглашений */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listAchievements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ачивки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPmUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PM-карточка пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PmUserResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listFraudChecks: {
        parameters: {
            query?: {
                limit?: number;
                decision?: "approve" | "hold" | "block";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Решения антифрода */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FraudCheckListResponse"];
                };
            };
        };
    };
    getLatestSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Последняя симуляция */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getLatestEval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Последний relevance eval */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
